### ISSUE TITLE
[TypeError] Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by zllovesuki** [grantcarthew/node-rethinkdb-job-queue#54]
Stack trace:
```
TypeError: Cannot read property 'status' of undefined
    at resultAction (/opt/dermail-api/node_modules/rethinkdb-job-queue/dist/queue-process.js:100:13)
    at nextHandler (/opt/dermail-api/node_modules/rethinkdb-job-queue/dist/queue-process.js:105:48)
    at callback (/opt/dermail-api/Worker.js:266:20)
    at /opt/dermail-api/Worker.js:470:24
    at tryCatcher (/opt/dermail-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/dermail-api/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/dermail-api/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/dermail-api/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/dermail-api/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/dermail-api/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/dermail-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/dermail-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

package version: 2.3.1 (this problem appears after I upgrade from 2.1.1 to 2.3.1)

the error was thrown in the callback function `next()` with an undefined value as the only argument

**Comment by grantcarthew** [comment]
Looking into it now.

**Comment by grantcarthew** [comment]
v2.3.2 published. Fixed.
Thanks Rachel @zllovesuki
